
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: comp6452-backend
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=6452-jwt-secret-key
      - DATABASE_URL=sqlite:////app/instance/docker_app.db
    volumes:
      - backend_data:/app/instance
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: comp6452-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge